type User {
  id: Int
  name: String
  products: [Product]
}

type Query {
  users: [User]
  user(id: Int): User
}

input UserInput {
  name: String
}

type Mutation {
  createUser(newUser: UserInput): User!
}